name: brain
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - pip
  - pip:
    - mne==1.6.1
    - fastapi==0.104.1
    - uvicorn==0.24.0
    - cloudinary==1.36.0
    - python-dotenv==1.0.0
    - pydantic==2.5.0
    - pydantic-core==2.14.1
    - aiofiles==23.2.1
